"""initial schema

Revision ID: 7dd1e775871e
Revises:
Create Date: 2026-09-23 01:59:47.288947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7dd1e775871e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.String(length=255), nullable=False),
        sa.Column("thread_id", sa.String(length=255), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "demo",
                "gmail",
                name="email_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("sender", sa.String(length=320), nullable=False),
        sa.Column("sender_name", sa.String(length=255), nullable=True),
        sa.Column("recipients", sa.JSON(), nullable=False),
        sa.Column("subject", sa.String(length=998), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "CLASSIFIED",
                "DRAFT_GENERATED",
                "UNDER_REVIEW",
                "APPROVED",
                "SENT",
                "REJECTED",
                "EDIT_REQUIRED",
                "FAILED",
                "ERROR",
                name="email_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=40), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=True),
        sa.Column("needs_manual_review", sa.Boolean(), nullable=False),
        sa.Column("review_reasons", sa.JSON(), nullable=False),
        sa.Column("spam_signals", sa.JSON(), nullable=False),
        sa.Column("processing_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status != 'SENT' OR sent_at IS NOT NULL", name=op.f("ck_emails_sent_has_timestamp")
        ),
        sa.CheckConstraint(
            "processing_attempts >= 0", name=op.f("ck_emails_attempts_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_emails")),
        sa.UniqueConstraint("message_id", name=op.f("uq_emails_message_id")),
    )
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_emails_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_emails_status"), ["status"], unique=False)
        batch_op.create_index("ix_emails_status_received", ["status", "received_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_emails_thread_id"), ["thread_id"], unique=False)

    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column(
            "text_source",
            sa.Enum(
                "text_layer",
                "ocr",
                "none",
                name="text_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("parse_error", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_attachments_size_non_negative")),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.id"],
            name=op.f("fk_attachments_email_id_emails"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attachments_email_id"), ["email_id"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=True),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.id"],
            name=op.f("fk_audit_logs_email_id_emails"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_email_id"), ["email_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_event_type"), ["event_type"], unique=False)

    op.create_table(
        "classifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("raw_category", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("requires_action", sa.Boolean(), nullable=False),
        sa.Column("unknown_category", sa.Boolean(), nullable=False),
        sa.Column("low_confidence", sa.Boolean(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("llm_attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_classifications_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.id"],
            name=op.f("fk_classifications_email_id_emails"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classifications")),
    )
    with op.batch_alter_table("classifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_classifications_email_id"), ["email_id"], unique=False)

    op.create_table(
        "drafts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_draft_id", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "ai",
                "admin_edit",
                name="draft_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=998), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("missing_information", sa.JSON(), nullable=False),
        sa.Column("reason_for_reply", sa.Text(), nullable=False),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("requires_human_review", name=op.f("ck_drafts_always_human_review")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_drafts_version_positive")),
        sa.ForeignKeyConstraint(
            ["email_id"], ["emails.id"], name=op.f("fk_drafts_email_id_emails"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_draft_id"],
            ["drafts.id"],
            name=op.f("fk_drafts_parent_draft_id_drafts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drafts")),
        sa.UniqueConstraint("email_id", "version", name="uq_drafts_email_version"),
    )
    with op.batch_alter_table("drafts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_drafts_email_id"), ["email_id"], unique=False)
        batch_op.create_index(
            "uq_drafts_one_current_per_email",
            ["email_id"],
            unique=True,
            sqlite_where=sa.text("is_current = 1"),
            postgresql_where=sa.text("is_current"),
        )

    op.create_table(
        "extractions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.Integer(), nullable=False),
        sa.Column("schema_name", sa.String(length=32), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("missing_information", sa.JSON(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.id"],
            name=op.f("fk_extractions_email_id_emails"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extractions")),
    )
    with op.batch_alter_table("extractions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_extractions_email_id"), ["email_id"], unique=False)

    op.create_table(
        "processing_errors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.Integer(), nullable=True),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.String(length=500), nullable=False),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.id"],
            name=op.f("fk_processing_errors_email_id_emails"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_errors")),
    )
    with op.batch_alter_table("processing_errors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_processing_errors_email_id"), ["email_id"], unique=False
        )

    op.create_table(
        "approvals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.Integer(), nullable=False),
        sa.Column("draft_id", sa.Integer(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "APPROVED",
                "REJECTED",
                "EDIT_REQUIRED",
                name="approval_decision",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("approver", sa.String(length=100), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision != 'APPROVED' OR draft_id IS NOT NULL",
            name=op.f("ck_approvals_approved_has_draft"),
        ),
        sa.CheckConstraint(
            "length(trim(approver)) > 0", name=op.f("ck_approvals_approver_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["drafts.id"],
            name=op.f("fk_approvals_draft_id_drafts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.id"],
            name=op.f("fk_approvals_email_id_emails"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approvals_email_id"), ["email_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approvals_email_id"))

    op.drop_table("approvals")
    with op.batch_alter_table("processing_errors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_processing_errors_email_id"))

    op.drop_table("processing_errors")
    with op.batch_alter_table("extractions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extractions_email_id"))

    op.drop_table("extractions")
    with op.batch_alter_table("drafts", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_drafts_one_current_per_email",
            sqlite_where=sa.text("is_current = 1"),
            postgresql_where=sa.text("is_current"),
        )
        batch_op.drop_index(batch_op.f("ix_drafts_email_id"))

    op.drop_table("drafts")
    with op.batch_alter_table("classifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_classifications_email_id"))

    op.drop_table("classifications")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_event_type"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_email_id"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attachments_email_id"))

    op.drop_table("attachments")
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_emails_thread_id"))
        batch_op.drop_index("ix_emails_status_received")
        batch_op.drop_index(batch_op.f("ix_emails_status"))
        batch_op.drop_index(batch_op.f("ix_emails_category"))

    op.drop_table("emails")
    # ### end Alembic commands ###
