"""classification red_flags

Revision ID: 820826a79669
Revises: 7dd1e775871e
Create Date: 2026-09-23 02:28:40.422782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "820826a79669"
down_revision: Union[str, Sequence[str], None] = "7dd1e775871e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classifications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("red_flags", sa.JSON(), server_default=sa.text("'[]'"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classifications", schema=None) as batch_op:
        batch_op.drop_column("red_flags")

    # ### end Alembic commands ###
