"""extraction grounding columns

Revision ID: c9ab24095a2e
Revises: 820826a79669
Create Date: 2026-09-23 02:49:33.812332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9ab24095a2e"
down_revision: Union[str, Sequence[str], None] = "820826a79669"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("extractions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ungrounded_fields", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("llm_attempts", sa.Integer(), server_default=sa.text("1"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("extractions", schema=None) as batch_op:
        batch_op.drop_column("llm_attempts")
        batch_op.drop_column("ungrounded_fields")

    # ### end Alembic commands ###
