"""approval hash and send marker

Revision ID: a09200123075
Revises: 1614a47b285a
Create Date: 2026-09-23 03:30:24.626064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a09200123075"
down_revision: Union[str, Sequence[str], None] = "1614a47b285a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("content_sha256", sa.String(length=64), nullable=True))
        # Added by hand: autogenerate does not detect CHECK constraints. No APPROVED rows
        # can exist before this revision (no approval code shipped earlier).
        batch_op.create_check_constraint(
            op.f("ck_approvals_approved_has_hash"),
            "decision != 'APPROVED' OR content_sha256 IS NOT NULL",
        )

    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.add_column(sa.Column("send_started_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.drop_column("send_started_at")

    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_constraint(op.f("ck_approvals_approved_has_hash"), type_="check")
        batch_op.drop_column("content_sha256")

    # ### end Alembic commands ###
