"""rfc message id

Revision ID: 90eb8e672c80
Revises: a09200123075
Create Date: 2026-09-23 05:24:14.522138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90eb8e672c80"
down_revision: Union[str, Sequence[str], None] = "a09200123075"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rfc_message_id", sa.String(length=998), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.drop_column("rfc_message_id")

    # ### end Alembic commands ###
