"""draft warnings and prompt version

Revision ID: 1614a47b285a
Revises: c9ab24095a2e
Create Date: 2026-09-23 03:02:36.087446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1614a47b285a"
down_revision: Union[str, Sequence[str], None] = "c9ab24095a2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("drafts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prompt_version", sa.String(length=32), nullable=True))
        batch_op.add_column(
            sa.Column("warnings", sa.JSON(), server_default=sa.text("'[]'"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("drafts", schema=None) as batch_op:
        batch_op.drop_column("warnings")
        batch_op.drop_column("prompt_version")

    # ### end Alembic commands ###
